web:
  image: berpj/web-demo
  ports:
    - "80:80"
  links:
    - app
app:
  image: berpj/app-demo
  links:
    - db
  ports:
    - "3000:3000"
  environment:
    RAILS_ENV: production
    DB_HOST: db
    DB_PORT: 5432
    DB_ADAPTER: postgresql
    DB_DATABASE: tododb
    DB_USER: todouser
    DB_PASS: myPwd
db:
  image: macadmins/postgres
  volumes:
    - ./dbdata:/var/lib/postgresql
  environment:
    DB_NAME: tododb
    DB_USER: todouser
    DB_PASS: myPwd
